#!/bin/bash
# example.sh - Show how to use semantic

# Print header with emphasis on when email is required
echo "==================================================="
echo "           Semantic - Usage Examples                "
echo "==================================================="
echo ""
echo "SERVER MODE (no email required):"
echo "-------------------"
echo "1. Start server with Ollama:"
echo "   cargo run -- --provider ollama"
echo ""
echo "2. Start server with Claude (default):"
echo "   cargo run"
echo ""
echo ""
echo "CLI MODE (email required):"
echo "-------------------"
echo "3. Analyze text with Ollama:"
echo "   cargo run -- --provider ollama --email user@example.com \"analyze this text\""
echo ""
echo "4. Analyze text with Claude:"
echo "   cargo run -- --provider claude --email user@example.com \"analyze this text\""
echo ""
echo "5. Show help:"
echo "   cargo run -- --help"
echo ""
echo "IMPORTANT: Email is required ONLY when analyzing a sentence!"
echo ""
echo "Remember to set up your .env file with CLAUDE_API_KEY if using Claude."
